"""empty message

Revision ID: 0dc7ba52c18c
Revises: 9926ab57a350
Create Date: 2018-06-25 09:52:27.183894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dc7ba52c18c'
down_revision = '9926ab57a350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('filename', sa.String(), nullable=True))
    op.drop_column('results', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('results', 'filename')
    # ### end Alembic commands ###
