"""empty message

Revision ID: 5d7fe68dfe4b
Revises: 0dc7ba52c18c
Create Date: 2018-07-12 10:27:37.035354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d7fe68dfe4b'
down_revision = '0dc7ba52c18c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direct',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename_orig', sa.String(), nullable=True),
    sa.Column('filename_s3', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('direct')
    # ### end Alembic commands ###
